# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-02-11 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_part', '0003_auto_20210211_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='average_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='average_wait',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfoentry',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfoentry',
            name='load_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfoentry',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfoentry',
            name='wait_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfoentry',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
