# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-01-28 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
