# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-02-19 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_part', '0004_auto_20210211_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='max_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='max_wait',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='min_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='min_wait',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='n_of_load',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='n_of_wait',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='website_link',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='companyinfoentry',
            name='company_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_part.CompanyInfo'),
        ),
        migrations.AddField(
            model_name='companyinfoentry',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='companyinfoentry',
            name='website_link',
            field=models.CharField(default='', max_length=128),
        ),
    ]
